### ISSUE TITLE
ibus-table speed up

### ISSUE THREAD

**Issue by mozbugbox** [acevery/ibus-table#10]
Please consider the patch from google ibus issue #1328 to speed up ibus-table with large phrase tables.

https://code.google.com/p/ibus/issues/detail?id=1328

**Comment by heiher** [comment]
https://github.com/mike-fabian/ibus-table/commit/d68a20c1aece6092ee58b57927a554d16a425dfa
https://github.com/mike-fabian/ibus-table/commit/b10c2ddfa9f003a529efc7bb4f2309e899f64444
https://github.com/mike-fabian/ibus-table/commit/ccb0effe6dc15c81e4782588f709fd6dca4cb41d

**Comment by mozbugbox** [comment]
Fixed
